server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    name: waimai
    url: jdbc:mysql://localhost:3306/waimai
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.southwind.entity