server:
  port: 8020
spring:
  application:
    name: menu
  datasource:
    name: waimai
    url: jdbc:mysql://localhost:3306/waimai
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.southwind.entity